services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: mathias
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: sae
    volumes:
      - ./wordpress:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
    networks:
      - sae_network

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: sae
      MYSQL_USER: mathias
      MYSQL_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - sae_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: mathias
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - sae_network

networks:
  sae_network:
    driver: bridge