services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: mathias
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: sae
    volumes:
      - ./wordpress:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
    networks:
      - sae_network

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: sae
      MYSQL_USER: mathias
      MYSQL_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
      - ./save/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - sae_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      # Indique à phpMyAdmin son URI derrière le proxy
      PMA_ABSOLUTE_URI: http://192.168.100.10/phpmyadmin/ 
    # Port 8080 supprimé : Nginx gèrera le routage
    depends_on:
      - mariadb
    networks:
      - sae_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Ajout pour Symfony
      - "8081:8081"  # Ajout pour phpMyAdmin
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      sae_network:
        ipv4_address: 192.168.100.10
    depends_on:
      - wordpress
      - phpmyadmin
      - symfony

  symfony:
    build:
      context: .
      dockerfile: Dockerfile.symfony
    container_name: symfony
    restart: unless-stopped
    # Port 8001 supprimé : Nginx gèrera le routage
    environment:
      DATABASE_URL: "mysql://mathias:root@mariadb:3306/sae?serverVersion=mariadb-10.11.2&charset=utf8mb4"
    volumes:
      - ./symfony_app:/var/www/html
    depends_on:
      - mariadb
    networks:
      - sae_network

networks:
  sae_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24